using NF.Network.Task;


namespace Game
{	
	using UnityEngine;
	using System.Collections.Generic;
	using AutoGenerated.Transfer;
	using System.Collections;
	using System.Threading;
	using System;
	public class _main : MonoBehaviour
	{
		IEnumerator Start()
		{
			var sender = new Sender ();
			var t = sender.Hello (1, 2);
			/*
			var tt = t as SlimTask;
			while (!tt.IsCompleted) {
				yield return null;
			}
			*/

			yield return t.WaitHandle;
			var r = t.Result;
			print (r);
		}
	}
}
