require 'json'
require 'fileutils'

task :test_server do
  # pip install protobuf
  message_dir = "@MESSAGE"
  output_dir = "test_server"
  mkdir_p output_dir
  sh "protoc -I=#{message_dir} --python_out=#{output_dir} #{message_dir}/*.proto"
  Dir.chdir(output_dir) do
    sh "python main.py"
  end
end

task :default do
  # brew install protobuf
  # sh 'git clone https://github.com/google/protobuf.git'

  # Dir.chdir('protobuf/csharp/src/Google.Protobuf') do
  #   contents = File.read('project.json')
  #   my_hash = JSON.parse(contents)
  #   my_hash['frameworks'] = {"net35" => {}}
  #   File.write('project.json', my_hash.to_json)

  #   sh 'dotnet restore'
  #   sh 'dotnet build --configuration Debug'
  # end
  # sh 'curl https://raw.githubusercontent.com/netpyoung/nf.template/master/setup.rb | ruby'


  # mkdir_p 'unity_project/Assets/external/protobuf'
  # cp_r 'protobuf/csharp/src/Google.Protobuf/bin/Debug', 'unity_project/Assets/external/protobuf'

  message_dir = "@MESSAGE"
  output_dir = "@CUSTOM/AutoGenerated.Message/output"
  mkdir_p output_dir
  sh "protoc -I=#{message_dir} --csharp_out=#{output_dir} #{message_dir}/*.proto"

  Dir.chdir('@CUSTOM/AutoGenerated.Message') do
    sh 'dotnet restore'
    sh "dotnet build"
  end

  Dir.chdir('NF.Network.Protocol.Interface') do
    sh 'dotnet restore'
    sh "dotnet build"
  end

  Dir.chdir('NF.Network.Transfer.Protobuf') do
    sh 'dotnet restore'
    sh "dotnet build"
  end

end
