// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: hello.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace AutoGenerated.Message {

  /// <summary>Holder for reflection information generated from hello.proto</summary>
  public static partial class HelloReflection {

    #region Descriptor
    /// <summary>File descriptor for hello.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static HelloReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgtoZWxsby5wcm90bxIIcHJvdG9jb2wiIAoGUUhlbGxvEgoKAnExGAEgASgF",
            "EgoKAnEyGAIgASgFIiAKBlJIZWxsbxIKCgJyMRgBIAEoBRIKCgJyMhgCIAEo",
            "BUIYqgIVQXV0b0dlbmVyYXRlZC5NZXNzYWdlYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::AutoGenerated.Message.QHello), global::AutoGenerated.Message.QHello.Parser, new[]{ "Q1", "Q2" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AutoGenerated.Message.RHello), global::AutoGenerated.Message.RHello.Parser, new[]{ "R1", "R2" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class QHello : pb::IMessage<QHello> {
    private static readonly pb::MessageParser<QHello> _parser = new pb::MessageParser<QHello>(() => new QHello());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<QHello> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AutoGenerated.Message.HelloReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QHello() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QHello(QHello other) : this() {
      q1_ = other.q1_;
      q2_ = other.q2_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public QHello Clone() {
      return new QHello(this);
    }

    /// <summary>Field number for the "q1" field.</summary>
    public const int Q1FieldNumber = 1;
    private int q1_;
    /// <summary>
    //// hello description.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Q1 {
      get { return q1_; }
      set {
        q1_ = value;
      }
    }

    /// <summary>Field number for the "q2" field.</summary>
    public const int Q2FieldNumber = 2;
    private int q2_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Q2 {
      get { return q2_; }
      set {
        q2_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as QHello);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(QHello other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Q1 != other.Q1) return false;
      if (Q2 != other.Q2) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Q1 != 0) hash ^= Q1.GetHashCode();
      if (Q2 != 0) hash ^= Q2.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Q1 != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Q1);
      }
      if (Q2 != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Q2);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Q1 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Q1);
      }
      if (Q2 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Q2);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(QHello other) {
      if (other == null) {
        return;
      }
      if (other.Q1 != 0) {
        Q1 = other.Q1;
      }
      if (other.Q2 != 0) {
        Q2 = other.Q2;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Q1 = input.ReadInt32();
            break;
          }
          case 16: {
            Q2 = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class RHello : pb::IMessage<RHello> {
    private static readonly pb::MessageParser<RHello> _parser = new pb::MessageParser<RHello>(() => new RHello());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RHello> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AutoGenerated.Message.HelloReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RHello() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RHello(RHello other) : this() {
      r1_ = other.r1_;
      r2_ = other.r2_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RHello Clone() {
      return new RHello(this);
    }

    /// <summary>Field number for the "r1" field.</summary>
    public const int R1FieldNumber = 1;
    private int r1_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int R1 {
      get { return r1_; }
      set {
        r1_ = value;
      }
    }

    /// <summary>Field number for the "r2" field.</summary>
    public const int R2FieldNumber = 2;
    private int r2_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int R2 {
      get { return r2_; }
      set {
        r2_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RHello);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RHello other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (R1 != other.R1) return false;
      if (R2 != other.R2) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (R1 != 0) hash ^= R1.GetHashCode();
      if (R2 != 0) hash ^= R2.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (R1 != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(R1);
      }
      if (R2 != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(R2);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (R1 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(R1);
      }
      if (R2 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(R2);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RHello other) {
      if (other == null) {
        return;
      }
      if (other.R1 != 0) {
        R1 = other.R1;
      }
      if (other.R2 != 0) {
        R2 = other.R2;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            R1 = input.ReadInt32();
            break;
          }
          case 16: {
            R2 = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
