/***************************
 * DO NOT MODIFY THIS FILE
 ***************************/

using System.Threading.Tasks;
using Google.Protobuf;
using NF.Network.Protocol.Interface;
using NF.Results;

namespace AutoGenerated.Transfer
{
    public abstract partial class BaseSender : INetworkSender<IMessage>
    {
        public abstract Task<Result<R, int>> Send<R>(IMessage reqMessage) where R : IMessage, new();
    }
}