/***************************
 * DO NOT MODIFY THIS FILE
 ***************************/

using NF.Results;
using AutoGenerated.Message;
using AutoGenerated.Interface;
using System.Threading.Tasks;

namespace AutoGenerated.Protocol
{
    public partial class BaseSender : IHello
    {
        #region IHello implementation
        public Task<Result<RHello, int>> Hello(QHello q)
        {
            return Send<RHello>(q);
        }

        public Task<Result<RHello, int>> Hello(System.Int32 Q1, System.Int32 Q2)
        {
            return Hello (new QHello() { Q1 = Q1, Q2 = Q2 });
        }
        #endregion
   }
}
