/***************************
 * DO NOT MODIFY THIS FILE
 ***************************/

using System.Threading.Tasks;
using NF.Results;
using AutoGenerated.Message;

namespace AutoGenerated.Interface
{
    public interface IHello: IMessageSender
    {
        Task<Result<RHello, int>> Hello(QHello q);
        Task<Result<RHello, int>> Hello(System.Int32 Q1, System.Int32 Q2);
    }
}
