using System.Threading.Tasks;
using NF.Results;
using Google.Protobuf;
using AutoGenerated.Interface;

namespace AutoGenerated.Protocol
{
	public abstract partial class BaseSender : INetworkSender<IMessage>
    {
        public abstract Task<Result<R, int>> Send<R>(IMessage reqMessage) where R : IMessage, new();
    }
}
