/***************************
 * DO NOT MODIFY THIS FILE
 ***************************/
using System.Threading.Tasks;
using NF.Results;
using AutoGenerated.Message;

namespace AutoGenerated.Interface
{
    public interface IWorld: IMessageSender
    {
        Task<Result<RWorld, int>> World(QWorld q);
        Task<Result<RWorld, int>> World(System.Int32 Q1, System.Int32 Q2);
    }
}
