/***************************
 * DO NOT MODIFY THIS FILE
 ***************************/

using NF.Results;
using AutoGenerated.Message;
using AutoGenerated.Interface;
using System.Threading.Tasks;

namespace AutoGenerated.Protocol
{
    public partial class BaseSender : IWorld
    {
        #region IWorld implementation
        public Task<Result<RWorld, int>> World(QWorld q)
        {
            return Send<RWorld>(q);
        }

        public Task<Result<RWorld, int>> World(System.Int32 Q1, System.Int32 Q2)
        {
            return World (new QWorld() { Q1 = Q1, Q2 = Q2 });
        }
        #endregion
   }
}
