namespace NF.Tools.ProtocolFlow
{
    public class Config
    {
        public string MessageDll { get; set; }
        public string OutputInterface { get; set; }
        public string OutputProtocol { get; set; }
        public string OutputDir { get; set; }

        public string NamespaceInterface { get; set; } = "AutoGenerated.Interface";
        public string NamespaceProtocol { get; set; } = "AutoGenerated.Protocol";
        public string NamespaceMessage { get; set; } = string.Empty;

        public string LiquidInterface { get; set; }// = "interface.liquid";
        public string LiquidProtocol { get; set; }// = "protocol.liquid";

        public string RegRequest { get; set; } = "(?<protocol>Q(?<name>.*))";
        public string RegResponse { get; set; } = "(?<protocol>R(?<name>.*))";
    }
}