# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hello.proto',
  package='protocol',
  syntax='proto3',
  serialized_pb=_b('\n\x0bhello.proto\x12\x08protocol\" \n\x06QHello\x12\n\n\x02q1\x18\x01 \x01(\x05\x12\n\n\x02q2\x18\x02 \x01(\x05\" \n\x06RHello\x12\n\n\x02r1\x18\x01 \x01(\x05\x12\n\n\x02r2\x18\x02 \x01(\x05\x42\x19\xaa\x02\x16\x41utoGenerated.Protocolb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_QHELLO = _descriptor.Descriptor(
  name='QHello',
  full_name='protocol.QHello',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='q1', full_name='protocol.QHello.q1', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='q2', full_name='protocol.QHello.q2', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=57,
)


_RHELLO = _descriptor.Descriptor(
  name='RHello',
  full_name='protocol.RHello',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='r1', full_name='protocol.RHello.r1', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='r2', full_name='protocol.RHello.r2', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=91,
)

DESCRIPTOR.message_types_by_name['QHello'] = _QHELLO
DESCRIPTOR.message_types_by_name['RHello'] = _RHELLO

QHello = _reflection.GeneratedProtocolMessageType('QHello', (_message.Message,), dict(
  DESCRIPTOR = _QHELLO,
  __module__ = 'hello_pb2'
  # @@protoc_insertion_point(class_scope:protocol.QHello)
  ))
_sym_db.RegisterMessage(QHello)

RHello = _reflection.GeneratedProtocolMessageType('RHello', (_message.Message,), dict(
  DESCRIPTOR = _RHELLO,
  __module__ = 'hello_pb2'
  # @@protoc_insertion_point(class_scope:protocol.RHello)
  ))
_sym_db.RegisterMessage(RHello)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\252\002\026AutoGenerated.Protocol'))
# @@protoc_insertion_point(module_scope)
